// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApEa_INaCn-5m4GCJ_Um7PBYr5wiqFHSU',
    appId: '1:486286615269:android:ff93308d0ca82879daaa0c',
    messagingSenderId: '486286615269',
    projectId: 'cityride-fcad0',
    databaseURL: 'https://cityride-fcad0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cityride-fcad0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApEa_INaCn-5m4GCJ_Um7PBYr5wiqFHSU',
    appId: '1:486286615269:ios:ff93308d0ca82879daaa0c',
    messagingSenderId: '486286615269',
    projectId: 'cityride-fcad0',
    databaseURL: 'https://cityride-fcad0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cityride-fcad0.firebasestorage.app',
    iosBundleId: 'com.jaikisan.card',
  );

  // Static method to get options from environment or google-services.json
  static FirebaseOptions getConfiguredOptions() {
    // You can configure based on platform
    // For Android: values from google-services.json are auto-configured
    // For iOS: values from GoogleService-Info.plist are auto-configured
    
    return currentPlatform;
  }
}
