// Email OTP Request Models
class EmailOTPRequest {
  final String email;

  EmailOTPRequest({required this.email});

  Map<String, dynamic> toJson() {
    return {
      'LoginEmailOTP': [
        {
          'Email': email,
          'OTP': '', // OTP will be generated by server
        }
      ]
    };
  }
}

// Email OTP Response Models
class EmailOTPResponse {
  final List<LoginEmailOTP> loginEmailOTP;
  final List<ResponseData> response;

  EmailOTPResponse({
    required this.loginEmailOTP,
    required this.response,
  });

  factory EmailOTPResponse.fromJson(Map<String, dynamic> json) {
    return EmailOTPResponse(
      loginEmailOTP: (json['LoginEmailOTP'] as List?)
          ?.map((e) => LoginEmailOTP.fromJson(e))
          .toList() ?? [],
      response: (json['RESPONSE'] as List?)
          ?.map((e) => ResponseData.fromJson(e))
          .toList() ?? [],
    );
  }
}

class LoginEmailOTP {
  final String email;
  final String otp;

  LoginEmailOTP({
    required this.email,
    required this.otp,
  });

  factory LoginEmailOTP.fromJson(Map<String, dynamic> json) {
    return LoginEmailOTP(
      email: json['Email'] ?? '',
      otp: json['OTP'] ?? '',
    );
  }
}

// Validate OTP Request Models
class ValidateOTPRequest {
  final String email;
  final String otp;

  ValidateOTPRequest({
    required this.email,
    required this.otp,
  });

  Map<String, dynamic> toJson() {
    return {
      'EmailID': email,
      'OTP': otp,
    };
  }
}

// Validate OTP Response Models
class ValidateOTPResponse {
  final List<LoginDetails> loginDetails;
  final List<ResponseData> response;

  ValidateOTPResponse({
    required this.loginDetails,
    required this.response,
  });

  factory ValidateOTPResponse.fromJson(Map<String, dynamic> json) {
    return ValidateOTPResponse(
      loginDetails: (json['LoginDetails'] as List?)
          ?.map((e) => LoginDetails.fromJson(e))
          .toList() ?? [],
      response: (json['RESPONSE'] as List?)
          ?.map((e) => ResponseData.fromJson(e))
          .toList() ?? [],
    );
  }
}

class LoginDetails {
  final String tokenCode;
  final String email;
  final String name;
  final String mobile;
  final String address;
  final String gender;
  final String dateOfBirth;
  final String cardNo;
  final String contactID;
  final String latitude;
  final String longitude;
  final String buildingRadius;

  LoginDetails({
    required this.tokenCode,
    required this.email,
    required this.name,
    required this.mobile,
    required this.address,
    required this.gender,
    required this.dateOfBirth,
    required this.cardNo,
    required this.contactID,
    required this.latitude,
    required this.longitude,
    required this.buildingRadius,
  });

  factory LoginDetails.fromJson(Map<String, dynamic> json) {
    return LoginDetails(
      tokenCode: json['TokenCode'] ?? '',
      email: json['Email'] ?? '',
      name: json['Name'] ?? '',
      mobile: json['Mobile'] ?? '',
      address: json['Address'] ?? '',
      gender: json['Gender'] ?? '',
      dateOfBirth: json['DateofBirth'] ?? '',
      cardNo: json['CardNo'] ?? '',
      contactID: json['ContactID'] ?? '',
      latitude: json['Latitude'] ?? '',
      longitude: json['Longitude'] ?? '',
      buildingRadius: json['BuildingRadius'] ?? '',
    );
  }
}

// Common Response Model
class ResponseData {
  final String responseMessage;
  final String responseCode;

  ResponseData({
    required this.responseMessage,
    required this.responseCode,
  });

  factory ResponseData.fromJson(Map<String, dynamic> json) {
    return ResponseData(
      responseMessage: json['ResponseMessage'] ?? '',
      responseCode: json['ResponseCode'] ?? '',
    );
  }

  bool get isSuccess => responseCode == '200';
}
